version: "3.8"
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=devredispass
    command: redis-server --requirepass ${REDIS_PASSWORD:-devredispass}

  web:
    build: .
    image: derelia/big_data_lab_four:latest
    depends_on:
      - kafka
      - redis
    command: bash -c "uvicorn src.app:app --host 0.0.0.0 --port 8090"
    ports:
      - "8090:8090"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=predictions
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
